# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D0D1D1
background         #081216
cursor             #7D7755

active_tab_foreground     #081216
active_tab_background     #D0D1D1
inactive_tab_foreground   #D0D1D1
inactive_tab_background   #081216

active_border_color   #D0D1D1
inactive_border_color #081216
bell_border_color     #9E9A8E

color0      #9C9D9E
color1		#9E9A8E
color2		#8B8F93
color3		#837D71
color4		#807B73
color5		#746D40
color6		#3F4D4D
color7		#5F5D55
color8		#949084
color9		#D3CEBD
color10		#B9BFC4
color11		#AFA697
color12		#ABA599
color13		#9B9255
color14		#536766
color15		#E1DED5
