# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0F1011)
$foreground = rgb(F0EEE8)
$color0 = rgb(383939)
$color1 = rgb(3F4D4D)
$color2 = rgb(746D40)
$color3 = rgb(807B73)
$color4 = rgb(837D71)
$color5 = rgb(8B8F93)
$color6 = rgb(9E9A8E)
$color7 = rgb(E1DED5)
$color8 = rgb(9D9B95)
$color9 = rgb(536766)
$color10 = rgb(9B9255)
$color11 = rgb(ABA599)
$color12 = rgb(AFA697)
$color13 = rgb(B9BFC4)
$color14 = rgb(D3CEBD)
$color15 = rgb(E1DED5)
