# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# default Monitor config

# Monitor Configuration
# See Hyprland wiki for more details
# https://wiki.hyprland.org/Configuring/Monitors/
# Configure your Display resolution, offset, scale and Monitors here, use `hyprctl monitors` to get the info.

monitor = HDMI-A-1, highrr,auto,1


